config/routes.rb
Rails.application.routes.draw do
  get 'recbooks/new'

  get 'sessionbooks/new'

  get 'books/list'

  get 'books/new'

  get 'sessionmembers/new'

  get 'members/new'

  get 'sessions/new'
  
  get 'admins/new'

  root 'static_pages#home'
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'admins#new'
  get 'signupmember' => 'members#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'loginmember' => 'sessionmembers#new'
  post 'loginmember' => 'sessionmembers#create'
  delete 'logoutmember' => 'sessionmembers#destroy'
  get 'memberslist' => 'members#index'
  get 'books' => 'books#new'
  get 'bookslist' => 'books#index'
  get 'recbooks' => 'recbooks#new'
  get 'recbookslist' => 'recbooks#index'
  get 'approve' => 'books#addrecbook'
  get 'searchbook' => 'books#search'
  get 'editbook' => 'books#edit'
  get 'click' => 'sessionbooks#new'
  post 'click' => 'sessionbooks#create'
  delete 'clickout' => 'sessionbooks#destroy'
  get 'bookslistlib' => 'books#indexlib'
  get 'editbooklib' => 'books#editlib'

  resources :recbooks
  resources :admins
  resources :members
  resources :books

end

app/views/admins/edit.html.erb
<% provide(:title, "Edit admin") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@admin) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      <%= f.label :email %>
      <%= f.text_field :email, class: 'form-control' %>
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>

app/views/admins/index.html.erb
<% provide(:title, 'All admins') %>
<h1>All Admins</h1>

<ul class="admins">
  <% @admins.each do |admin| %>
    <li>
      <%= admin.name %>, <%= admin.email %> |  <%= link_to "delete", admin, method: :delete %>
    </li>
  <% end %>
</ul>

app/views/admins/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Admin Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@admin) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <%= f.label :email %>
      <%= f.text_field :email %>
      <%= f.label :password %>
      <%= f.password_field :password %>
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>
      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/admins/show.html.erb
<h2><%= @admin.name %>, <%= @admin.email %></h2>
<h2><%= link_to "Edit Profile", edit_admin_path(current_admin) %></h2>
<h2><%= link_to "Create New Admin", signup_path, class: "btn btn-lg btn-primary" %></h2>
<h2><%= link_to "List Admin", admins_path %></h2>
<h2><%= link_to "List Lib Member", members_path %></h2>
<h2><%= link_to "Add a book", books_path %></h2>
<h2><%= link_to "List all books", bookslist_path %></h2>
<h2><%= link_to "List new suggested books", recbookslist_path %></h2>