config/routes.rb
Rails.application.routes.draw do
  get 'recbooks/new'

  get 'sessionbooks/new'

  get 'books/list'

  get 'books/new'

  get 'sessionmembers/new'

  get 'members/new'

  get 'sessions/new'
  
  get 'admins/new'

  root 'static_pages#home'
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'admins#new'
  get 'signupmember' => 'members#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'loginmember' => 'sessionmembers#new'
  post 'loginmember' => 'sessionmembers#create'
  delete 'logoutmember' => 'sessionmembers#destroy'
  get 'memberslist' => 'members#index'
  get 'books' => 'books#new'
  get 'bookslist' => 'books#index'
  get 'recbooks' => 'recbooks#new'
  get 'recbookslist' => 'recbooks#index'
  get 'approve' => 'books#addrecbook'
  get 'searchbook' => 'books#search'
  get 'editbook' => 'books#edit'
  get 'click' => 'sessionbooks#new'
  post 'click' => 'sessionbooks#create'
  delete 'clickout' => 'sessionbooks#destroy'
  get 'bookslistlib' => 'books#indexlib'
  get 'editbooklib' => 'books#editlib'

  resources :recbooks
  resources :admins
  resources :members
  resources :books

end

app/models/book.rb
class Book < ActiveRecord::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def show
    @book = Book.find(params[:id])
  end
  
  def new
    @book = Book.new
  end

  def list
  end
  
  def index
    @books = Book.all
  end
  
  def indexlib
    @books = Book.all
  end
  
  def access
    @book = Book.find_by(params[:id])
  end
  
  def edit
    @book = Book.find(params[:id])
  end
  
  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to @book
    else
      render 'new'
    end
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update_attributes(book_params)
      redirect_to @book
    else
      render 'edit'
    end
  end
  
  def addrecbook
    @book = Book.new(params[:book])
    if @book.save
      render 'edit'
    else
      render 'new'
    end
  end
  
  def search
    @book = Book.new;
    #redirect_to @book
  end
  
  def destroy
    Book.find(params[:id]).destroy
    redirect_to bookslist_url
  end
  
  private
  
    def suggested_book_params
      params.require(:book).permit(:isbn, :title, :description, :author)
    end
    def book_params
      params.require(:book).permit(:isbn, :title, :description, :author, :status)
    end
  
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/access.html.erb
<% provide(:title, "Edit Book") %>
<h1>Update your Info</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@book) do |f| %>
      <%= f.label :isbn %>
      <%= f.text_field :isbn, class: 'form-control' %>
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>
      
      <%= f.label :description %>
      <%= f.text_field :description, class: 'form-control' %>
      <%= f.label :author %>
      <%= f.text_field :author, class: 'form-control' %>
      
      <%= f.label :status %>
      <%= f.select :status, [['Available','Available'],['CheckedOut','CheckedOut']] %>
      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>

app/views/books/editlib.html.erb
<% provide(:title, "Edit book") %>
<h1>your book info</h1>

<%= current_book.isbn %>
<%= current_book.title %>
<%= current_book.description %>
<%= current_book.author %>

app/views/books/index.html.erb
<% provide(:title, 'All books') %>
<h1>All books</h1>
 <table style="table-layout: fixed; width: auto">

  <% @books.each do |book| %>
  <tr>
      <td><%=book.isbn%><td>
      <td><%=book.title%><td>
      <td><%=book.description%><td>
      <td><%=book.author%><td>
      <td><%=book.status%><td>
  </tr>
  <% end %>

  </table>

app/views/books/indexlib.html.erb
<% provide(:title, 'All books') %>
<h1>All Admins</h1>

<ul class="books">
  <% @books.each do |book| %>
    <li>
      <%=session[:book_value]=book.id%>
      <%=link_to book.isbn, editbooklib_path(current_book) %>, 
      <%= book.status %>

    </li>
  <% end %>
</ul>

app/views/books/new.html.erb
<% provide(:title, 'books') %>
<h1>books</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@book) do |f| %>
      <%= f.label :isbn %>
      <%= f.text_field :isbn %>

      <%= f.label :title %>
      <%= f.text_field :title %>

      <%= f.label :description %>
      <%= f.text_field :description %>

      <%= f.label :author %>
      <%= f.text_field :author %>

      <%= f.label :status %>
      <%= f.select :status, [['Available','Available'],['CheckedOut','CheckedOut']] %>
      
      <%= "\n" %>

      <%= f.submit "Create my book", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/books/search.html.erb
<% provide(:title, 'Searchbooks') %>
<h1>Search books</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@book) do |f| %>
      <%= f.label :isbn %>
      <%= f.text_field :isbn %>

      <%= f.label :title %>
      <%= f.text_field :title %>

      <%= f.label :description %>
      <%= f.text_field :description %>

      <%= f.label :author %>
      <%= f.text_field :author %>

      <%= f.label :status %>
      <%= f.text_field :status %>
      
      <%= "\n" %>
      <%= f.submit "Search", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/books/show.html.erb
<table style="width:100%">
  <tr>
    <td>ISBN</td>
    <td>Title</td>
    <td>Description</td>
    <td>Author</td>
    <td>Status</td>
  </tr>
  <tr>
      <%=session[:book_value]=params[:id]%>
      <td><%= link_to @book.isbn, editbook_path(current_book)%><td>
      <td><%=@book.title%><td>
      <td><%=@book.description%><td>
      <td><%=@book.author%><td>
      <td><%=@book.status%><td>
      
  </tr>

</table>