config/routes.rb
Rails.application.routes.draw do
  get 'recbooks/new'

  get 'sessionbooks/new'

  get 'books/list'

  get 'books/new'

  get 'sessionmembers/new'

  get 'members/new'

  get 'sessions/new'
  
  get 'admins/new'

  root 'static_pages#home'
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'admins#new'
  get 'signupmember' => 'members#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'loginmember' => 'sessionmembers#new'
  post 'loginmember' => 'sessionmembers#create'
  delete 'logoutmember' => 'sessionmembers#destroy'
  get 'memberslist' => 'members#index'
  get 'books' => 'books#new'
  get 'bookslist' => 'books#index'
  get 'recbooks' => 'recbooks#new'
  get 'recbookslist' => 'recbooks#index'
  get 'approve' => 'books#addrecbook'
  get 'searchbook' => 'books#search'
  get 'editbook' => 'books#edit'
  get 'click' => 'sessionbooks#new'
  post 'click' => 'sessionbooks#create'
  delete 'clickout' => 'sessionbooks#destroy'
  get 'bookslistlib' => 'books#indexlib'
  get 'editbooklib' => 'books#editlib'

  resources :recbooks
  resources :admins
  resources :members
  resources :books

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title><%= full_title(yield(:title))%></title>
<%= stylesheet_link_tag 'application', media: 'all',
'data-turbolinks-track' =>true%>
<%= javascript_include_tag'application', 'data-turbolinks-track' =>true%>
<%= csrf_meta_tags%>
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->
</head>
<body>
<header class="navbar navbar-fixed-top navbar-inverse">
<div class="container">
<%= link_to "LibSys", root_path %>
<nav>
<ul class="nav navbar-nav pull-right">
<li><%= link_to "Home", root_path %></li>
<li><%= link_to "Help", help_path %></li>

<% if logged_in? %>
    <li><%= link_to current_admin.name, current_admin %></li>
<% else %>
    <li><%= link_to "Admin Log in", login_path %></li>
<% end %>
<li><%= link_to "Admin Log out", logout_path, method: "delete" %></li>

<% if logged_in_member? %>
    <li><%= link_to current_member.name, current_member %></li>
<% else %>
    <li><%= link_to "Lib Member Log in", loginmember_path %></li>
<% end %>
<li><%= link_to "Lib Member Log out", logoutmember_path, method: "delete" %></li>
<li><%= link_to "Search books", searchbook_path %></li>
</ul>
</nav>
</div>
</header>
<div class="container">
<%= yield %>
</div>
</body>
</html>