config/routes.rb
Rails.application.routes.draw do
  get 'recbooks/new'

  get 'sessionbooks/new'

  get 'books/list'

  get 'books/new'

  get 'sessionmembers/new'

  get 'members/new'

  get 'sessions/new'
  
  get 'admins/new'

  root 'static_pages#home'
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'admins#new'
  get 'signupmember' => 'members#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'loginmember' => 'sessionmembers#new'
  post 'loginmember' => 'sessionmembers#create'
  delete 'logoutmember' => 'sessionmembers#destroy'
  get 'memberslist' => 'members#index'
  get 'books' => 'books#new'
  get 'bookslist' => 'books#index'
  get 'recbooks' => 'recbooks#new'
  get 'recbookslist' => 'recbooks#index'
  get 'approve' => 'books#addrecbook'
  get 'searchbook' => 'books#search'
  get 'editbook' => 'books#edit'
  get 'click' => 'sessionbooks#new'
  post 'click' => 'sessionbooks#create'
  delete 'clickout' => 'sessionbooks#destroy'
  get 'bookslistlib' => 'books#indexlib'
  get 'editbooklib' => 'books#editlib'

  resources :recbooks
  resources :admins
  resources :members
  resources :books

end

app/models/member.rb
class Member < ActiveRecord::Base
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }
end

app/controllers/members_controller.rb
class MembersController < ApplicationController

  before_action :logged_in_member_yes, only: [:show, :edit, :update, :destroy]
  before_action :correct_member, only: [:show, :edit, :update]  
  def show
    @member = Member.find(params[:id])
  end

  def new
    @member = Member.new
  end
  
  def create
    @member = Member.new(member_params)
    if @member.save
      redirect_to @member
    else
      render 'new'
    end
  end
  
  def edit
    @member = Member.find(params[:id])
  end
  
  def index
    @members = Member.all
  end
  
  def update
    @member = Member.find(params[:id])
    if @member.update_attributes(member_params)
      redirect_to @member
    else
      render 'edit'
    end
  end
  
  def destroy
    Member.find(params[:id]).destroy
    redirect_to memberslist_url
  end
  
  def member_params
      params.require(:member).permit(:name, :email, :password, :password_confirmation)
  end
  
    def logged_in_member_yes
      unless logged_in_member?
        redirect_to loginmember_url
      end
    end
    
    def correct_member
      @member = Member.find(params[:id])
      redirect_to(root_url) unless @member == current_member
    end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/edit.html.erb
<% provide(:title, "Edit lib member") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@member) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      <%= f.label :email %>
      <%= f.text_field :email, class: 'form-control' %>
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>

app/views/members/index.html.erb
<% provide(:title, 'All lib members') %>
<h1>All lib members</h1>

<ul class="members">
  <% @members.each do |member| %>
    <li>
      <%= member.name %>, <%= member.email %> |  <%= link_to "delete", member, method: :delete %>
    </li>
  <% end %>
</ul>

app/views/members/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Lib Member Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@member) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <%= f.label :email %>
      <%= f.text_field :email %>
      <%= f.label :password %>
      <%= f.password_field :password %>
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>
      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/members/show.html.erb
<h2><%= @member.name %>, <%= @member.email %></h2>
<h2><%= link_to "Edit Profile", edit_member_path(current_member) %></h2>
<h2><%= link_to "Suggest a book", recbooks_path %></h2>